# nome do aplicativo
spring.application.name=api

# configuração do banco h2 em mémoria
spring.datasource.url=jdbc:h2:mem:coinquestdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ativa o painel visual do banco de dados no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=false

# configura o hibernate para criar as tabelas automaticamente com base no java
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# mostra no console do VScode os comandos SQL que o java estiver executando
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true 
